Remove 'parent' argument from wx StatusBarManager
enthought/pyface pull request #1192
Opened 2023-01-10 16:18 UTC by greschd

Another small fix:

Remove the 'parent' argument from 'StatusBarManager.destroy' in the wx backend. The argument is unused, and doesn't match the interface definition.

If you prefer keeping the argument (to not break applications which may pass it explicitly?), I'd propose adding a default `=None`, and emitting a deprecation warning.

2023-01-10 17:00 UTC, corranwebster requested changes
Once again, thanks for the PR.  This probably needs a corresponding change to the call here: https://github.com/enthought/pyface/blob/acccc5ea314f006d8734a51bfb0074c8906beefa/pyface/ui/wx/application_window.py#L225

2023-01-11 09:56 UTC, corranwebster commented
> I wonder if we should add some kind of test?

There are tests for the create/destroy aspects of the `StatusBarManager` API that would have detected the problem here: https://github.com/enthought/pyface/blob/9aeb3bd56bb6bec52b244132a928416e40d4b878/pyface/tests/test_application_window.py#L222-L252

Unfortunately those tests need the `GuiTestAssistant` class which we haven't yet integrated for WxPython (see #614 and #266 - the primary obstacle is not writing the class, it's getting everything running correctly once you have it).

So the long and short of it is, no, no need to write a test, and this looks good to go.

2023-01-11 09:57 UTC, corranwebster approved these changes

2023-01-11 09:58 UTC, merged

2023-01-11 11:09 UTC, greschd commented
Thanks for the review, and the context on testing!