Stop running CI on traits 6.0
enthought/pyface pull request #865
Opened 2021-01-22 22:26 UTC by aaronayres35

fixes #781 

This PR updates the travis.yml file to require traits 6.1+ not 6.0+.  It also removes a traits version check that prevented data_view test from being run for traits !=6.1.  Not we will want these tests to run on 6.2+ as well.

2021-01-25 05:32 UTC, rahulporuri requested changes
Apart from these two changes, we will also want to specify in `setup.py` that we require `traits>=6.2.0`.

2021-01-25 05:32 UTC, rahulporuri commented on .travis.yml
> +    - env: RUNTIME=3.6 TOOLKITS="pyqt5 wx" TRAITS_REQUIRES="^=6.1"
Not sure why we need to test against both the latest version of traits (6.2) and the older version (6.1) for the pyqt5 and wx toolkits. I think we can remove the env where we set `TRAITS_REQUIRES`

2021-01-25 16:35 UTC, rahulporuri approved these changes
I think this LGTM.

The fishy thing (that i suspect but have not verified) is that traits 6.1.1 is probably installed via edm first - and then updated to traits 6.2.0 via pip because of the change in version requirement. Can you confirm this?

If that is indeed the case, I would hold off on merging this PR until traits 6.2.0 is available via edm - and rerun CI on this PR, just to be super safe (and to calm my super paranoia).

2021-01-25 18:29 UTC, aaronayres35 commented
> I think this LGTM.
> 
> The fishy thing (that i suspect but have not verified) is that traits 6.1.1 is probably installed via edm first - and then updated to traits 6.2.0 via pip because of the change in version requirement. Can you confirm this?
> 
> If that is indeed the case, I would hold off on merging this PR until traits 6.2.0 is available via edm - and rerun CI on this PR, just to be super safe (and to calm my super paranoia).

It looks like CI is actually just being run with traits 6.1 from edm currently, even though the setup.py explicitly requires traits 6.2+.  There are no explicit version restrictions on the CI config files as the PR currently stands.  I will wait until 6.2 is available through edm and rerun CI on this PR

2021-01-27 06:00 UTC, rahulporuri commented
Rerunning CI now that Travis 6.2.0 is available via EDM.

2021-01-27 06:16 UTC, rahulporuri commented
Looks like traits 6.2.0 is now being used in the CI. Still LGTM.

2021-01-27 12:58 UTC, merged